#cloud-config

# DEPENDENCIES mongo:3.0.9

write_files:
  - path: /etc/issue
    content: |
      UC6 Meter Appliance 5.0.0 Build 29 *beta*

      Welcome to the UC6 Meter Appliance

      To register the meter:
        1 - Open a browser to https://\4{ens192}
        2 - Follow the wizard

      --------------------------------------------
       Meter Admin Console : https://\4{ens192}
       Default Shell User : core
       Default Shell Password : 6fusion
      --------------------------------------------

      * Note that this is a beta build of the UC6 Meter Appliance *
  - path: /home/core/.bash_profile
    permissions: 0644
    owner: core
    content: |
      [[ -f ~/.bashrc ]] && . ~/.bashrc
      alias wizard="docker exec -it meter-registration /bin/sh"
      alias mongo="docker exec -it meter-database mongo 6fusion_meter_development"
      alias rollback='cgpt prioritize "$(cgpt find -t coreos-usr | grep --invert-match "$(findmnt --noheadings --raw --output=source --target=/usr)")'
  - path: /var/lib/vmware_meter/.keep
    permissions: 0600
    owner: root

coreos:
  units:
    - name: systemd-timesyncd.service
      command: start
      enable: true
    - name: ntpd.service
      command: stop
      mask: true
    - name: locksmithd.service
      command: stop
      mask: true
    - name: update-engine.service
      command: stop
      mask: true
    - name: disable-transparent-huge-pages.service
      command: start
      content: |
        [Unit]
        Description=Disable Transparent Huge Pages

        [Service]
        Type=oneshot
        ExecStart=/bin/sh -c "/usr/bin/echo never | tee /sys/kernel/mm/transparent_hugepage/enabled"
        ExecStart=/bin/sh -c "usr/bin/echo never | tee /sys/kernel/mm/transparent_hugepage/defrag"
    - name: vmtoolsd.service
      command: start
      content: |
        [Unit]
        Description=VMware Tools Agent
        Documentation=http://open-vm-tools.sourceforge.net/
        ConditionVirtualization=vmware

        [Service]
        ExecStartPre=/usr/bin/ln -sfT /usr/share/oem/vmware-tools /etc/vmware-tools
        ExecStart=/usr/share/oem/bin/vmtoolsd
        TimeoutStopSec=5
    - name: ovfnetworkd.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=OVF Network Agent
        ConditionVirtualization=vmware
        Requires=vmtoolsd.service
        After=vmtoolsd.service
        Before=systemd-networkd.service

        [Service]
        ExecStart=/usr/share/oem/bin/ovfnetworkd.sh

        [Install]
        WantedBy=multi-user.target
    - name: meter-database.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=UC6 Meter Database
        Requires=docker.service
        After=docker.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker stop -t 60 meter-database
        ExecStartPre=-/usr/bin/docker rm meter-database
        ExecStart=/usr/bin/docker run -p 27017:27017 --name meter-database -v /:/host --volumes-from meterDB mongo:3.0.9
        ExecStop=/usr/bin/docker stop -t 60 meter-database
        RestartSec=30s
        Restart=always

        [Install]
        WantedBy=multi-user.target
    - name: meter-infrastructure-collector.service
      enable: false
      content: |
        [Unit]
        Description=Infrastructure Collector
        Requires=docker.service
        Requires=meter-database.service
        After=docker.service
        After=meter-database.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker stop -t 60 infrastructure-collector
        ExecStartPre=-/usr/bin/docker rm infrastructure-collector
        ExecStart=/usr/bin/docker run  --link meter-database:mongo --name infrastructure-collector 6fusion/vmware-collector:beta ruby bin/infrastructure-collector.rb
        ExecStop=/usr/bin/docker stop -t 60 infrastructure-collector
        RestartSec=30s
        Restart=always

        [Install]
        WantedBy=multi-user.target
    - name: meter-inventory-collector.service
      enable: false
      content: |
        [Unit]
        Description=Inventory Collector
        Requires=docker.service
        Requires=meter-database.service
        After=docker.service
        After=meter-database.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker stop -t 60 inventory-collector
        ExecStartPre=-/usr/bin/docker rm inventory-collector
        ExecStart=/usr/bin/docker run --link meter-database:mongo --name inventory-collector 6fusion/vmware-collector:beta ruby bin/inventory-collector.rb
        ExecStop=/usr/bin/docker stop -t 60 inventory-collector
        RestartSec=30s
        Restart=always

        [Install]
        WantedBy=multi-user.target
    - name: meter-metrics-collector.service
      enable: false
      content: |
        [Unit]
        Description=Metrics Collector
        Requires=docker.service
        Requires=meter-database.service
        After=docker.service
        After=meter-database.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker stop -t 60 metrics-collector
        ExecStartPre=-/usr/bin/docker rm metrics-collector
        ExecStart=/usr/bin/docker run --link meter-database:mongo --name metrics-collector 6fusion/vmware-collector:beta ruby bin/metrics-collector.rb
        ExecStop=/usr/bin/docker stop -t 60 metrics-collector
        RestartSec=30s
        Restart=always

        [Install]
        WantedBy=multi-user.target
    - name: meter-missing-readings-handler.service
      enable: false
      content: |
        [Unit]
        Description=Missing Readings Handler
        Requires=docker.service
        Requires=meter-database.service
        After=docker.service
        After=meter-database.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker stop -t 60 missing-readings-handler
        ExecStartPre=-/usr/bin/docker rm missing-readings-handler
        ExecStart=/usr/bin/docker run --link meter-database:mongo --name missing-readings-handler 6fusion/vmware-collector:beta ruby bin/missing-local-readings-handler.rb
        ExecStop=/usr/bin/docker stop -t 60 missing-readings-handler
        RestartSec=30s
        Restart=always

        [Install]
        WantedBy=multi-user.target
    - name: meter-uc6-connector.service
      enable: false
      content: |
        [Unit]
        Description=UC6 Connector
        Requires=docker.service
        Requires=meter-database.service
        After=docker.service
        After=meter-database.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker stop -t 60 uc6-connector
        ExecStartPre=-/usr/bin/docker rm uc6-connector
        ExecStart=/usr/bin/docker run --link meter-database:mongo --name uc6-connector 6fusion/vmware-collector:beta ruby bin/uc6-connector.rb
        ExecStop=/usr/bin/docker stop -t 60 uc6-connector
        RestartSec=30s
        Restart=always

        [Install]
        WantedBy=multi-user.target

  oem:
    bug-report-url: "https://github.com/coreos/bugs/issues"
    id: vmware
    name: VMWare
    version-id: "9.10.0-r1"

