FROM alpine:3.2
MAINTAINER 6fusion dev <dev@6fusion.com>

ENV BUILD_PACKAGES build-base curl-dev libffi-dev gcc git zlib-dev
ENV RUBY_PACKAGES ruby ruby-bundler ruby-dev ruby-io-console ruby-nokogiri
ENV RUNTIME_PACKAGES ca-certificates bash
ENV CONTAINER metrics
ENV SECRETS_PATH /var/run/secrets/vmwarecollector
ENV METER_ENV production

WORKDIR /usr/src/app
COPY . /usr/src/app

RUN  apk update && \
     apk upgrade && \
     apk add $BUILD_PACKAGES $RUBY_PACKAGES $DEV_PACKAGES $RUNTIME_PACKAGES && \
     bundle install --without test && \
     rm -rf .git .gitignore .vagrant init-ssl* secrets_example spec ssl test Vagrantfile && \
     rm -rf /var/cache/apk/*


ENTRYPOINT ["ruby", "bin/metrics-collector.rb"]

