FROM alpine:3.2
MAINTAINER 6fusion dev <dev@6fusion.com>

ENV BUILD_PACKAGES build-base curl-dev libffi-dev gcc git zlib-dev
ENV RUBY_PACKAGES nodejs ruby ruby-bundler ruby-dev ruby-io-console ruby-nokogiri
ENV DEV_PACKAGES bash vim
ENV RUNTIME_PACKAGES ca-certificates

ENV METER_ENV development
ENV CONTAINER metrics
ENV SECRETS_PATH /var/run/secrets/vmwarecollector

RUN apk update && \
    apk upgrade && \
    apk add $BUILD_PACKAGES $RUBY_PACKAGES $DEV_PACKAGES $RUNTIME_PACKAGES && \
    mkdir -p /usr/src/app

WORKDIR  /usr/src/app
COPY . /usr/src/app

# Update and install all of the required packages.
# At the end, remove the apk cache

RUN bundle install

ENTRYPOINT ["ruby", "bin/metrics-collector.rb"]

