FROM alpine:3.2
MAINTAINER 6fusion dev <dev@6fusion.com>

ENV BUILD_PACKAGES build-base curl-dev libffi-dev gcc zlib-dev
ENV RUBY_PACKAGES ruby ruby-bundler ruby-dev ruby-nokogiri
ENV RUNTIME_PACKAGES ca-certificates bash
ENV CONTAINER inventory
ENV SECRETS_PATH /var/run/secrets/vmwarecollector
ENV METER_ENV production


WORKDIR /usr/src/app
COPY . /usr/src/app

RUN apk update && \
  apk upgrade && \
  apk add $BUILD_PACKAGES $RUBY_PACKAGES $RUNTIME_PACKAGES && \
  bundle install --without test && \
  rm -rf .git .gitignore .vagrant init-ssl* secrets_example spec ssl test Vagrantfile && \
  bundle clean --force && \
  apk del $BUILD_PACKAGES && \
  rm -rf /var/cache/apk/*


ENTRYPOINT ["ruby", "bin/inventory-collector.rb"]
