apiVersion: v1
kind: Template
metadata:
  name: vmware-collector
  annotations:
    displayName: "VMware Collector"
    description: "VMware Collector for vCenter 5.5+"
    pluginVersion: "0.11"
    meterVersion: ">=0.11"
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: 6fusion-vmware-collector
- apiVersion: v1
  kind: Service
  metadata:
    name: mongodb
    namespace: 6fusion-vmware-collector
    labels:
      6fusion-app: mongodb
  spec:
    ports:
    - port: 27017
      protocol: TCP
      name: mongodb-port
    selector:
      6fusion-app: mongodb
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: mongodb
    namespace: 6fusion-vmware-collector
    labels:
      6fusion-app: mongodb
  spec:
    replicas: 1
    selector:
      6fusion-app: mongodb
    template:
      metadata:
        name: mongodb
        labels:
          6fusion-app: mongodb
      spec:
        containers:
        - name: mongodb
          image: mongo:3.4.6
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /data/db
            name: mongodb
        volumes:
        - name: mongodb
          emptyDir: {}
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: 6fusion-vmwarecollector-master
    namespace: 6fusion-vmware-collector
    labels:
      6fusion-app: vmwarecollector-master
  spec:
    replicas: 1
    selector:
      6fusion-app: vmwarecollector-master
    template:
      metadata:
        name: 6fusion-vmwarecollector-master
        labels:
          6fusion-app: vmwarecollector-master
      spec:
        containers:
        - name: vmware-collector-inventory
          image: 6fusion/vmware-collector:alpha
          imagePullPolicy: IfNotPresent
          env:
          - name: VSPHERE_HOST
            valueFrom:
              secretKeyRef:
                key: host
                name: vcenter-secret
          - name: VSPHERE_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: vcenter-secret
          - name: VSPHERE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: vcenter-secret
          - name: VCENTER_DESCRIPTOR
            valueFrom:
              secretKeyRef:
                key: vcenter-descriptor
                name: vcenter-secret
          - name: VSPHERE_IGNORE_SSL_ERRORS
            valueFrom:
              secretKeyRef:
                key: ignore-ssl-errors
                name: vcenter-secret
          - name: METER_API_PROTOCOL
            valueFrom:
              secretKeyRef:
                key: api-protocol
                name: on-prem-secret
          - name: ON_PREM_API_HOST
            valueFrom:
              secretKeyRef:
                key: api-host
                name: on-prem-secret
          - name: ON_PREM_API_PORT
            valueFrom:
              secretKeyRef:
                key: api-port
                name: on-prem-secret
          - name: ORGANIZATION_ID
            valueFrom:
              secretKeyRef:
                key: organization-id
                name: on-prem-secret
          - name: DEFAULT_DISK_IO
            valueFrom:
              secretKeyRef:
                key: default-disk-io
                name: on-prem-secret
          - name: DEFAULT_WAN_IO
            valueFrom:
              secretKeyRef:
                key: default-wan-io
                name: on-prem-secret
          - name: DEFAULT_LAN_IO
            valueFrom:
              secretKeyRef:
                key: default-lan-io
                name: on-prem-secret
          volumeMounts:
          - name: vcenter-secret
            mountPath: /var/run/secrets/vmwarecollector/vsphere
          - name: on-prem-secret
            mountPath: /var/run/secrets/vmwarecollector/on-prem
        volumes:
        - name: vcenter-secret
          secret:
            secretName: vcenter-secret
        - name: on-prem-secret
          secret:
            secretName: on-prem-secret
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: 6fusion-vmwarecollector-metrics
    namespace: 6fusion-vmware-collector
    labels:
      6fusion-app: vmwarecollector-metrics
  spec:
    replicas: 1
    selector:
      6fusion-app: vmwarecollector-metrics
    template:
      metadata:
        name: 6fusion-vmwarecollector-metrics
        labels:
          6fusion-app: vmwarecollector-metrics
      spec:
        containers:
        - name: vmware-collector-metrics
          image: 6fusion/vmware-collector-metrics:alpha
          imagePullPolicy: IfNotPresent
          env:
          - name: VSPHERE_HOST
            valueFrom:
              secretKeyRef:
                key: host
                name: vcenter-secret
          - name: VSPHERE_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: vcenter-secret
          - name: VSPHERE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: vcenter-secret
          - name: VSPHERE_IGNORE_SSL_ERRORS
            valueFrom:
              secretKeyRef:
                key: ignore-ssl-errors
                name: vcenter-secret
          volumeMounts:
          - name: vcenter-secret
            mountPath: /var/run/secrets/vmwarecollector/vsphere
          - name: on-prem-secret
            mountPath: /var/run/secrets/vmwarecollector/on-prem
        volumes:
        - name: vcenter-secret
          secret:
            secretName: vcenter-secret
        - name: on-prem-secret
          secret:
            secretName: on-prem-secret
parameters:
#vSphere questions
- description: "Host address of vCenter"
  name: host
  displayName: "vCenter Host"
  section: vcenter-secret
  sectionDisplayName: vCenter
  validations:
    required: true
  type: string
- name: user
  displayName: "vCenter User"
  section: vcenter-secret
  sectionDisplayName: vCenter
  validations:
    required: true
  type: string
  description: "Account used for vCenter access"
- name: password
  section: vcenter-secret
  sectionDisplayName: vCenter
  displayName: "vCenter Password"
  validations:
    required: true
  type: password
  description: "vCenter account password"
- name: vcenter-descriptor
  displayName: "vCenter Descriptor"
  section: vcenter-secret
  sectionDisplayName: vCenter
  type: string
  description: "A short, descriptive name for the vCenter. Datacenters will be tagged with this prefix in the 6fusion Meter."
- name: ignore-ssl-errors
  section: vcenter-secret
  sectionDisplayName: vCenter
  displayName: "Ignore SSL validation errors?"
  validations:
    required: true
  type: boolean
  value: "true"
  description: "Do not perform strict SSL validation. Disable if using self-signed SSL certificates"
- name: readings-batch-size
  section: vcenter-secret
  sectionDisplayName: vCenter
  displayName: "Max Query Metrics"
  type: int
  value: "64"
  description: "Limit the number of machines per performance metrics query. Should match the vpxd.stats.maxquerymetrics vCenter setting"
# on prem questions
- name: api-host
  section: on-prem-secret
  sectionDisplayName: Meter
  type: string
  displayName: "Meter API Host"
  description: "Host address of 6fusion Meter"
  validations:
    required: true
  expandExpression: ${METER_API_HOST}
  advanced: true
- name: api-port
  section: on-prem-secret
  sectionDisplayName: Meter
  type: int
  displayName: "Meter API Port"
  description: "Host port of 6fusion Meter API"
  validations:
    required: true
  expandExpression: ${METER_API_PORT}
  advanced: true
- name: api-protocol
  section: on-prem-secret
  sectionDisplayName: Meter
  type: enum
  options:
    - http
    - https
  value: http
  advanced: true
- name: oauth-token
  section: on-prem-secret
  sectionDisplayName: Meter
  type: string
  displayName: "API Token"
  description: "OAuth authorization token for Meter API access"
- name: organization-id
  section: on-prem-secret
  sectionDisplayName: Meter
  type: string
  displayName: "Organization ID"
  description: "ID of organization object in the 6fusion Meter API"
  validations:
    required: true
  expandExpression: ${ORGANIZATION_ID}
  advanced: true
- name: registration-date
  section: on-prem-secret
  sectionDisplayName: Meter
  type: string
  displayName: "Registration Date"
  description: "Time to start collection from."
  hidden: true
  validations:
    required: true
  expandExpression: "`Time.now`"
  advanced: true
- name: machines-by-inv-timestamp
  section: on-prem-secret
  sectionDisplayName: Meter
  type: int
  displayName: "Machines per request"
  description: "Define the total of machines that are included on each request to obtain metrics from vsphere"
  validations:
    required: true
  advanced: true
  value: "500"  # TODO confirm this default
- name: default-disk-io
  section: on-prem-secret
  sectionDisplayName: Meter
  type: string
  displayName: "Default Disk I/O"
  description: "The value to use for Disk I/O if the collector cannot determine the actual disk I/O speed"
  validations:
    required: true
  value: "10"
  suffix: "Gbps"
- name: default-lan-io
  section: on-prem-secret
  sectionDisplayName: Meter
  type: string
  displayName: "Default LAN I/O"
  description: "The value to use for LAN I/O if the collector cannot determine the actual LAN I/O speed"
  validations:
    required: true
  value: "10"
  suffix: "Gbps"
- name: default-wan-io
  section: on-prem-secret
  sectionDisplayName: Meter
  type: string
  displayName: "Default WAN I/O"
  description: "The value to use for WAN I/O if the collector cannot determine the actual WAN I/O speed"
  validations:
    required: true
  value: "1"
  suffix: "Gbps"
