apiVersion: v1
kind: Namespace
metadata:
  name: 6fusion-vmware-collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 6fusion-vmwarecollector
  namespace: 6fusion-vmware-collector
---
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-secret
  namespace: 6fusion-vmware-collector
data:
  host: "BASE64_VALUE"                      # Host definition for vsphere
  user: "BASE64_VALUE"                      # User information for vpshere
  password: "BASE64_VALUE"                  # Password information for vsphere
  ignore-ssl-errors: "BASE64_VALUE"         # Ignore ssl-errors
  log-level: "BASE64_VALUE"                 # Define log level
  session-limit: "BASE64_VALUE"             # Total elements valuable for each session
---
apiVersion: v1
kind: Secret
metadata:
  name: on-prem-secret
  namespace: 6fusion-vmware-collector
data:
  api-host: "BASE64_VALUE"                  # Host definition for on-prem-api
  log-level: "BASE64_VALUE"                 # Defined level for showing elements in log (defaults to debug)
  api-endpoint: "BASE64_VALUE"              # Base API endpoint Defaults to /v1/api
  organization-id: "BASE64_VALUE"           # Organization ID on on-prem-api
  registration-date: "BASE64_VALUE"         # You need to set this value as the timestamp of the installation date
  machines-by-inv-timestamp: "BASE64_VALUE" # Define the total of machines that are included on each request to obtain metrics from vsphere
  inventoried-limit: "BASE64_VALUE"         # Define the limit of inventoried timestamps that each replica controller will take each round
  # batch_size: # Number of simultaneous requests for Vsphere
  #### OAUTH RELATED CONFIGURATION
  # oauth-endpoint: "BASE64_VALUE"          # Oauth path that will be included after api-host (defaults to oauth)
  # oauth-token: "BASE64_VALUE"             # Oauth 2 token to authenticate the requests
  # refresh-token: "BASE64_VALUE"           # Oauth 2 token that will be used if oauth-token expires (most of the times not required)
  # login-email: "BASE64_VALUE"             # Email for login the user in order to generate a new oauth token (not required if "oauth-token" provided)
  # login-password: "BASE64_VALUE"          # Password for login the user in order to generate a new oauth token (not required if "oauth-token" provided)
  # application-id: "BASE64_VALUE"          # Oauth Application id used to request a new oauth token (not required if "oauth-token" provided)
  # application-secret: "BASE64_VALUE"      # Oauth Application secret used to request a new oauth token (not required if "oauth-token" provided)
  # api-scope: "BASE64_VALUE"               # Scope required for oauth authentication
  #### Proxy related config (if required)
  # proxy-host: "BASE64_VALUE"              # Host required for proxy connection
  # proxy-port: "BASE64_VALUE"              # Port required for proxy connection
  # proxy-user: "BASE64_VALUE"              # User required for proxy connection
  # proxy-password: "BASE64_VALUE"          # Password required for proxy connection
---
apiVersion: v1
kind: Service
metadata:
  name: vmwarecollector-master
  namespace: 6fusion-vmware-collector
  labels:
    6fusion-app: vmwarecollector-master
spec:
  ports:
    - port: 27017
      protocol: TCP
      name: vmwarecollector-master-mongodb
  selector:
    6fusion-app: vmwarecollector-master
  type: NodePort
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: 6fusion-vmwarecollector-master
  namespace: 6fusion-vmware-collector5
  labels:
    6fusion-app: vmwarecollector-master
spec:
  replicas: 1
  selector:
    6fusion-app: vmwarecollector-master
  template:
    metadata:
      name: 6fusion-vmwarecollector-master
      labels:
        6fusion-app: vmwarecollector-master
    spec:
      containers:
      - name: vmware-collector-inventory
        image: 6fusion/vmware-collector:alpha
        imagePullPolicy: Always
        volumeMounts:
        - name: vsphere-secret
          mountPath: /var/run/secrets/vmwarecollector/vsphere
        - name: on-prem-secret
          mountPath: /var/run/secrets/vmwarecollector/on-prem
      - name: vmware-collector-mongodb
        image: mongo:3.2
      volumes:
      - name: vsphere-secret
        secret:
          secretName: vsphere-secret
      - name: on-prem-secret
        secret:
          secretName: on-prem-secret
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: 6fusion-vmwarecollector-metrics
  namespace: 6fusion-vmware-collector
  labels:
    6fusion-app: vmwarecollector-metrics
spec:
  replicas: 2
  selector:
    6fusion-app: vmwarecollector-metrics
  template:
    metadata:
      name: 6fusion-vmwarecollector-metrics
      labels:
        6fusion-app: vmwarecollector-metrics
    spec:
      containers:
      - name: vmware-collector-metrics
        image: 6fusion/vmware-collector-metrics # Docker image of the 6fusion VmWare Metrics Collector
        volumeMounts:
        - name: vsphere-secret
          mountPath: /var/run/secrets/vmwarecollector/vsphere
        - name: on-prem-secret
          mountPath: /var/run/secrets/vmwarecollector/on-prem
      volumes:
      - name: vsphere-secret
        secret:
          secretName: vsphere-secret
      - name: on-prem-secret
        secret:
          secretName: on-prem-secret
