# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
# require 'bundler'
# Bundler.require(:default, ENV['METER_ENV'] || :development)
$:.unshift '../lib', '../lib/shared', '../lib/models', 'lib', 'lib/shared', 'lib/models'

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks
