development:
  sessions:
    default:
      database: 6fusion_meter_development
      hosts:
        - localhost:27017
      log_level: info

test:
  sessions:
    default:
      database: 6fusion_meter_test
      hosts:
        - localhost:27017
      options:
        max_retries: 1
        retry_interval: 0

staging:
  sessions:
    default:
      database: 6fusion_meter_staging
      hosts:
        - localhost:27017
      options:
