development:
  api_host: http://localhost:3000
  login_email: uc6admin@6fusion.com
  login_password: 1q2w!Q@W
  log_level: debug
  oauth_endpoint: 'oauth'
  api_endpoint: 'api/v2'
  organization_id: 1
  application_id: a1acf7ed12ecd4a9857e5d01fc64df7c0bb86dc380cd4b4347fc7c979b1251e6
  application_secret: 70c57259e3d20edffd902a227110eb0f32e9e9a3386bbc61e0e62b501d7d6c68


test:
  host: localhost
  port: 3000
  user: uc6admin@6fusion.com
  password: 1q2w!Q@W
  oauth_endpoint: 'oauth'
  api_endpoint: 'api/v2'
  organization_id: 1

