TWO_MINUTES_IN_SECONDS = 120
FIVE_MINUTES_IN_SECONDS = 300
NINE_MINUTES_IN_SECONDS = 540
FITHTEEN_MINUTES_IN_SECONDS = 900
DEFAULT_SLEEP_TIME = 10
HOURS_IN_DAY = 24
MINIMUM_THREAD_PRIORITY = -100
REGULAR_THREAD_PRIORITY = 1
MINIMUM_VSPHERE_CONNECTIONS = 1
VSPHERE_CONNECTIONS_THRESHOLD = 4
VSPHERE_CONNECTIONS_LOOSENESS = 3
INVENTORY_WIGGLE_TIME = 55
TIMEOUT_LOCK_RELEASE_TIME = 60

