
default: &default
  clients:
    default:
      database: 6fusion
      hosts:
        - <%= "#{ENV['MONGODB_SERVICE_HOST']}:#{ENV['MONGODB_SERVICE_PORT']}" %>
      options:
        max_pool_size: 20

development:
  <<: *default

production:
  <<: *default
