
default: &default
  clients:
    default:
      database: 6fusion
      hosts:
        - <%= "#{ENV['MONGODB_SERVICE_HOST'] || 'localhost'}:#{ENV['MONGODB_SERVICE_PORT'] || '27017'}" %>
      options:
        max_pool_size: 20

development:
  <<: *default

production:
  <<: *default
