
default: &default
  clients:
    default:
      database: 6fusion
      hosts:
        - localhost:27017
      options:
        max_pool_size: 20

development:
  <<: *default

production:
  <<: *default
